# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from crazyflie_scripts/camera_msg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class camera_msg(genpy.Message):
  _md5sum = "512cd6d5f46f8407166dee36dcd1fc07"
  _type = "crazyflie_scripts/camera_msg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 ext_x_cam
float32 ext_y_cam
float32 track_x
float32 track_y
float32 track_z
float32 x_dir_tt
float32 y_dir_tt
float32 tg_yaw_t
"""
  __slots__ = ['ext_x_cam','ext_y_cam','track_x','track_y','track_z','x_dir_tt','y_dir_tt','tg_yaw_t']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ext_x_cam,ext_y_cam,track_x,track_y,track_z,x_dir_tt,y_dir_tt,tg_yaw_t

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(camera_msg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.ext_x_cam is None:
        self.ext_x_cam = 0.
      if self.ext_y_cam is None:
        self.ext_y_cam = 0.
      if self.track_x is None:
        self.track_x = 0.
      if self.track_y is None:
        self.track_y = 0.
      if self.track_z is None:
        self.track_z = 0.
      if self.x_dir_tt is None:
        self.x_dir_tt = 0.
      if self.y_dir_tt is None:
        self.y_dir_tt = 0.
      if self.tg_yaw_t is None:
        self.tg_yaw_t = 0.
    else:
      self.ext_x_cam = 0.
      self.ext_y_cam = 0.
      self.track_x = 0.
      self.track_y = 0.
      self.track_z = 0.
      self.x_dir_tt = 0.
      self.y_dir_tt = 0.
      self.tg_yaw_t = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8f().pack(_x.ext_x_cam, _x.ext_y_cam, _x.track_x, _x.track_y, _x.track_z, _x.x_dir_tt, _x.y_dir_tt, _x.tg_yaw_t))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.ext_x_cam, _x.ext_y_cam, _x.track_x, _x.track_y, _x.track_z, _x.x_dir_tt, _x.y_dir_tt, _x.tg_yaw_t,) = _get_struct_8f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8f().pack(_x.ext_x_cam, _x.ext_y_cam, _x.track_x, _x.track_y, _x.track_z, _x.x_dir_tt, _x.y_dir_tt, _x.tg_yaw_t))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.ext_x_cam, _x.ext_y_cam, _x.track_x, _x.track_y, _x.track_z, _x.x_dir_tt, _x.y_dir_tt, _x.tg_yaw_t,) = _get_struct_8f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8f = None
def _get_struct_8f():
    global _struct_8f
    if _struct_8f is None:
        _struct_8f = struct.Struct("<8f")
    return _struct_8f
