# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from crazyflie_scripts/camera_msg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class camera_msg(genpy.Message):
  _md5sum = "0528b01776a9faff38d86476b22e6f80"
  _type = "crazyflie_scripts/camera_msg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 ext_x
int32 ext_y
int32 t_x
int32 t_y
int32 x_dir_tt
int32 y_dir_tt
"""
  __slots__ = ['ext_x','ext_y','t_x','t_y','x_dir_tt','y_dir_tt']
  _slot_types = ['int32','int32','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ext_x,ext_y,t_x,t_y,x_dir_tt,y_dir_tt

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(camera_msg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.ext_x is None:
        self.ext_x = 0
      if self.ext_y is None:
        self.ext_y = 0
      if self.t_x is None:
        self.t_x = 0
      if self.t_y is None:
        self.t_y = 0
      if self.x_dir_tt is None:
        self.x_dir_tt = 0
      if self.y_dir_tt is None:
        self.y_dir_tt = 0
    else:
      self.ext_x = 0
      self.ext_y = 0
      self.t_x = 0
      self.t_y = 0
      self.x_dir_tt = 0
      self.y_dir_tt = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6i().pack(_x.ext_x, _x.ext_y, _x.t_x, _x.t_y, _x.x_dir_tt, _x.y_dir_tt))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.ext_x, _x.ext_y, _x.t_x, _x.t_y, _x.x_dir_tt, _x.y_dir_tt,) = _get_struct_6i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6i().pack(_x.ext_x, _x.ext_y, _x.t_x, _x.t_y, _x.x_dir_tt, _x.y_dir_tt))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.ext_x, _x.ext_y, _x.t_x, _x.t_y, _x.x_dir_tt, _x.y_dir_tt,) = _get_struct_6i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6i = None
def _get_struct_6i():
    global _struct_6i
    if _struct_6i is None:
        _struct_6i = struct.Struct("<6i")
    return _struct_6i
