// Generated by gencpp from file crazyflie_driver/HoverVel.msg
// DO NOT EDIT!


#ifndef CRAZYFLIE_DRIVER_MESSAGE_HOVERVEL_H
#define CRAZYFLIE_DRIVER_MESSAGE_HOVERVEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace crazyflie_driver
{
template <class ContainerAllocator>
struct HoverVel_
{
  typedef HoverVel_<ContainerAllocator> Type;

  HoverVel_()
    : header()
    , roll(0.0)
    , pitch(0.0)
    , yawrate(0.0)
    , thrust(0.0)  {
    }
  HoverVel_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , roll(0.0)
    , pitch(0.0)
    , yawrate(0.0)
    , thrust(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yawrate_type;
  _yawrate_type yawrate;

   typedef float _thrust_type;
  _thrust_type thrust;





  typedef boost::shared_ptr< ::crazyflie_driver::HoverVel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crazyflie_driver::HoverVel_<ContainerAllocator> const> ConstPtr;

}; // struct HoverVel_

typedef ::crazyflie_driver::HoverVel_<std::allocator<void> > HoverVel;

typedef boost::shared_ptr< ::crazyflie_driver::HoverVel > HoverVelPtr;
typedef boost::shared_ptr< ::crazyflie_driver::HoverVel const> HoverVelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crazyflie_driver::HoverVel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crazyflie_driver::HoverVel_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::crazyflie_driver::HoverVel_<ContainerAllocator1> & lhs, const ::crazyflie_driver::HoverVel_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yawrate == rhs.yawrate &&
    lhs.thrust == rhs.thrust;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::crazyflie_driver::HoverVel_<ContainerAllocator1> & lhs, const ::crazyflie_driver::HoverVel_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace crazyflie_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::crazyflie_driver::HoverVel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crazyflie_driver::HoverVel_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crazyflie_driver::HoverVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crazyflie_driver::HoverVel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazyflie_driver::HoverVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazyflie_driver::HoverVel_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crazyflie_driver::HoverVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "501e1b34ac346fbf5cf0ad513572908f";
  }

  static const char* value(const ::crazyflie_driver::HoverVel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x501e1b34ac346fbfULL;
  static const uint64_t static_value2 = 0x5cf0ad513572908fULL;
};

template<class ContainerAllocator>
struct DataType< ::crazyflie_driver::HoverVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crazyflie_driver/HoverVel";
  }

  static const char* value(const ::crazyflie_driver::HoverVel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crazyflie_driver::HoverVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 roll\n"
"float32 pitch\n"
"float32 yawrate\n"
"float32 thrust\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::crazyflie_driver::HoverVel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crazyflie_driver::HoverVel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yawrate);
      stream.next(m.thrust);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HoverVel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crazyflie_driver::HoverVel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crazyflie_driver::HoverVel_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yawrate: ";
    Printer<float>::stream(s, indent + "  ", v.yawrate);
    s << indent << "thrust: ";
    Printer<float>::stream(s, indent + "  ", v.thrust);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRAZYFLIE_DRIVER_MESSAGE_HOVERVEL_H
